#22 Get kind from local path
ForNeVeR/TruePath pull request #80
Opened 2024-07-19 16:37 UTC by Kataane

Add method that returns type from local path

2024-07-20 13:01 UTC, ForNeVeR requested changes
Great! There's couple of small issues.

2024-07-20 13:01 UTC, ForNeVeR commented on TruePath/LocalPath.cs
> +    public FileEntryKind? ReadKind()
I'd prefer this to be ported to `AbsolutePath` instead.

2024-07-20 14:35 UTC, Kataane commented
@ForNeVeR fixed

2024-08-11 20:35 UTC, ForNeVeR approved these changes
Thanks!

2024-08-11 20:45 UTC, merged